CREATE TABLE hike_tracker_hikes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES hike_tracker_users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    distance DECIMAL,
    time DECIMAL,
    elevation INTEGER,
    rating INTEGER,
    steps INTEGER,
    weather TEXT,
    notes TEXT,
    reference TEXT
);